version: "2"         # required to adjust maintainability checks

languages:
  JavaScript: true

checks:
  file-lines:
    enabled: true
    config:
      threshold: 700
  return-statements:
    enabled: true
    config:
      threshold: 6

exclude_patterns:
  - "lib/**"
  - "test/**"
  - "examples/**"
  - "LICENSE"
  - "LICENSE.md"
  - "README.md"
  - "package.json"
  - "**/*.d.ts"
