name: NPM Package Publish

on:
  push:
    branches:
      - main
      - next
      - alpha

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Check if version has been updated
        id: check
        uses: EndBug/version-check@095362f3cd50f690c8fa0e6afeea81834bd8d320 # v3.0.0

      - name: Setup Node
        # if: steps.check.outputs.changed == 'true'
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org/
          cache: npm

      - name: Setup Java (required by Firebase emulators)
        # if: steps.check.outputs.changed == 'true'
        uses: actions/setup-java@de7274f081f381c8f8158605e0321c36c376e2e6 # v6.0.1
        with:
          distribution: zulu
          java-version: 26

      - name: Cache Firebase Emulators
        # if: steps.check.outputs.changed == 'true'
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ~/.cache/firebase/emulators
          key: ${{ runner.os }}-firebase-emulators-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-firebase-emulators-

      - name: Install Dependencies
        # if: steps.check.outputs.changed == 'true'
        run: npm ci

      - name: Lint + Format Check
        # if: steps.check.outputs.changed == 'true'
        run: npm run check

      - name: Run Unit Tests + Coverage
        # if: steps.check.outputs.changed == 'true'
        run: npm run test:cov

      - name: Publish
        # if: steps.check.outputs.changed == 'true'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_REF: ${{ github.ref }}
        run: |
          gitBranch=${GITHUB_REF##*/}
          publishFlag=$(if [ "$GITHUB_REF" != 'refs/heads/main' ]; then eval echo '--tag $gitBranch'; else echo ''; fi;)
          echo "PACKAGE_VERSION=$(cat package.json | jq -r '.version')" >> $GITHUB_ENV
          npm publish $publishFlag

      - name: Upload Coverage
        # if: steps.check.outputs.changed == 'true'
        uses: codecov/codecov-action@303a32d7a59b442fa8d48b6a1cc6825c09c847a5 # v7.1.1
        with:
          token: ${{ secrets.CODE_COV }}

      - name: Create Release
        # if: github.ref == 'refs/heads/main' && steps.check.outputs.changed == 'true'
        uses: softprops/action-gh-release@efb35369e0ad2afab669f228072c1b0d510eae64 # v3.0.3
        with:
          tag_name: v${{ env.PACKAGE_VERSION }}
          name: v${{ env.PACKAGE_VERSION }}
          draft: false
          prerelease: false
